version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: booking
      MYSQL_USER: golang_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=golang_user
      - DB_PASSWORD=user_password
      - DB_NAME=booking
      - SERVER_ADDRESS=:8080
      - TOKEN_SECRET=my-ultra-secure-json-web-token-string
      - TOKEN_EXPIRED_IN=60m
      - TOKEN_MAXAGE=60
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt
      - ./www:/var/www/html
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email nguyenquocthang909@gmail.com --agree-tos --no-eff-email --force-renewal -d api.thangnq.studio
volumes:
  db_data:
