version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: booking
      MYSQL_USER: golang_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: golang_user
      DB_PASSWORD: user_password
      DB_NAME: booking
    restart: always

volumes:
  db_data:
